### ISSUE TITLE
Keybindings disappear from right-click menu

### ISSUE THREAD

**Issue by maximeplante** [UziTech/context-menu-remove#1]
Before activating the package:
<img width="432" alt="plein_ecran_18-03-20_13_44" src="https://user-images.githubusercontent.com/2321239/37672721-f08488de-2c44-11e8-9bf1-5207bb596c70.png">

After activating the package:
<img width="472" alt="plein_ecran_18-03-20_13_46" src="https://user-images.githubusercontent.com/2321239/37672789-13649772-2c45-11e8-8784-f4640a4a2698.png">

Environment:
* Atom `1.25.0`
* Nothing in `init.coffee`
* No package config in `config.cson`

**Comment by UziTech** [comment]
This package monkey patches much of the [atom.contextMenu](https://github.com/atom/atom/blob/master/src/context-menu-manager.coffee) from v1.13.0 and it looks like they added accelerators some time around v1.21.0

I would be open to a PR if you wanted to fix it.

**Comment by maximeplante** [comment]
I'm interested in making a PR for it. I'll get back to this once I have some free time.

**Comment by UziTech** [comment]
I just released v0.2.0 with the fix. Thanks
