### ISSUE TITLE
Will this be added to Atom?

### ISSUE THREAD

**Issue by bobjunga** [UziTech/context-menu-remove#8]
Hi Tony, I was just looking into how to suppress some context menu items that were showing up on a toolbar package I wrote and found your package. 

I just looked over the code. Nicely done!  Its interesting how you 'live patch' the atom.contextMenu object.

I am wondering though if you have any plans to submit this change as a PR against the Atom repo so that it gets maintained through refactors?  

--BobG

**Comment by UziTech** [comment]
I have already submitted a PR for this a while ago but they didn't want to merge it so I created it as a separate package.

https://github.com/atom/atom/pull/13746

**Comment by bobjunga** [comment]
that's too bad. I am glad you went ahead and made the package.   I have a PR submitted for the tee-view package that has gotten no response in several months. You inspired me to do a similar solution. If my code detects that the change is not present it asks the user to voice their support for the PR but now I am also including a live patch of tree-view so that it will go ahead and work anyway (at least until a future atom version breaks it) 

I have a real love hate relationship with Atom :)

--BobG
